# Generated by Django 5.2.15 on 2026-08-11 22:32

import django.db.models.deletion
from django.db import migrations, models


def seed_service_description_items(apps, schema_editor):
    Service = apps.get_model("services", "Service")
    ServiceDescriptionItem = apps.get_model("services", "ServiceDescriptionItem")

    engine_service = Service.objects.filter(title="Ремонт двигателя").first()
    if not engine_service:
        return

    items = [
        "Ремонт двигателя",
        "Замена прокладки ГБЦ",
        "Замена маслосъемных колпачков",
    ]

    for index, text in enumerate(items, start=1):
        ServiceDescriptionItem.objects.get_or_create(
            service=engine_service,
            text=text,
            defaults={"order": index},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_update_exhaust_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=220, verbose_name='Строка описания')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_items', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'строка описания',
                'verbose_name_plural': 'строки описания',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(seed_service_description_items, migrations.RunPython.noop),
    ]
