# Generated by Django 5.2.15 on 2026-08-11 22:37

from django.db import migrations, models


def normalize_description_item_order(apps, schema_editor):
    Service = apps.get_model("services", "Service")

    for service in Service.objects.all():
        items = service.description_items.order_by("order", "id")
        for order, item in enumerate(items, start=1):
            if item.order != order:
                item.order = order
                item.save(update_fields=["order"])


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicedescriptionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.RunPython(normalize_description_item_order, migrations.RunPython.noop),
    ]
