# Generated by Django 5.2.15 on 2026-08-13 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_service_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='service_photos/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=140, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Порядок')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='services.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'фото услуги',
                'verbose_name_plural': 'фотографии услуги',
                'ordering': ['order', 'id'],
            },
        ),
    ]
